### PR TITLE
Update intro.rst with a better producer/consumer

### PR DESCRIPTION
**Pull request by wojtossfm**
See gist for example test cases https://gist.github.com/wojtossfm/aede13446bb3b9e12942109f505058c1

The example code for the docs is prone to a race condition of the state of the tasks. If people replicate it they might wonder why they are losing messages (due to the cancel calls). The proposed change avoids the race condition. I tried to change as little as possible in the example.

If I'm missing something or something is unclear then let me know.

Just thought I'd chip in if I can. Great library by the way.

### CODE REVIEW

**Comment by aaugustin** [comment]
Indeed it's a good idea to avoid losing messages.

It looks like you're never removing completed tasks from the `pending` set. Are you sure this code works?

I'd expect something like:
```python



The code is even more convoluted that it used to be, I think the apology still applies, can you leave it there?

**Comment by wojtossfm** [comment]
But you don't need to remove tasks from the pending set. asyncio wait returns two sets - completed tasks and pending tasks. If a task is completed it is no longer in the pending set. Have a look at the gist in my comment. Go ahead and run it in case. It has similar code for asyncio (just without websockets) as examples what was wrong with the previous example and how this one works.

**Comment by aaugustin** [comment]
Right! I had missed that `done, pending = await asyncio.wait(...)` mutates `pending`. Sorry.

I'll do some testing when I have a bit more time, but at first sight, it looks good. Thanks!

**Comment by aaugustin** [comment]
The docs now contain a much more simple example, making this discussion moot.

Thanks for your help anyway and sorry for not being responsive!

**Pull request closed without merging**
