### PR TITLE
Provide a Sans-I/O interface

### LINKED ISSUE #466: Refactor to introduce a sans-I/O layer?
https://sans-io.readthedocs.io/how-to-sans-io.html

Bonus: write curio- or trio-compatible versions of the main APIs?

### PR DESCRIPTION
**Pull request by aaugustin**
Fix #466.

### CODE REVIEW

**Comment by cjerdonek** [comment]
I just finished reading [your blog post](https://fractalideas.com/blog/sans-io-when-rubber-meets-road/) about this effort. That's a superb writeup! Thanks!

One question I had when reading it: have you thought about whether there's an incremental way to start incorporating Sans I/O elements into your existing (non-Sans I/O) implementation? I'm wondering if it could help address some of the difficulties inherent in a "big bang" switch (as well as the need to maintain a parallel branch of such magnitude).

**Comment by aaugustin** [comment]
Well it's pretty hard to avoid a big bang:

- I did some preliminary work to remove some asyncio infrastructure, so the WebSocket protocol class is as close as possible to the transport.
- This PR prepares an entire Sans I/O implementation of the WebSocket protocol.
- Then at some point there's open-heart surgery to wire them together. I don't know how to avoid this.

**Comment by cjerdonek** [comment]
Just to clarify, I wasn't asking about the possibility of eliminating a big bang entirely, but rather decreasing the magnitude of the change by incrementally incorporating and using some elements of the Sans I/O implementation prior to completely switching over.

For example, could parts of the implementation be used under the hood without affecting the public-facing API too much? As another example, could the HTTP aspects being added first, prior to the websocket aspects?

**Comment by aaugustin** [comment]
In the PR, there's a lot of "moving + changing await to yield from + refactoring tests" which results in large changes that aren't really new code.

It's quite hard to perform "socket transplantation" i.e. switching a network socket connected to asyncio utilities over to a sans I/O stack, or vice versa. Technically it must be possible (transfer the buffer over if needed) but it's far from trivial.

**Comment by aaugustin** [comment]
This PR now contains a fairly complete Sans-I/O implementation of the WebSocket protocol. It doesn't include:

- porting the asyncio-based implementation on top of this new code — this will take quite a bit of work
- documentation for the Sans-I/O bits

For all the usual reasons against long running branches with huge changes, I'm planning to merge this now.

**Pull request merged**
