### PR TITLE
Allow custom arguments to EventLoop.create_connection to support proxies / custom transport 

### PR DESCRIPTION
**Pull request by FraMecca**
As of #221

### CODE REVIEW

**Comment by aaugustin** [comment]
Good. Now you need a test to ensure coverage remains at 100%. Most likely it should go in test_client_server.py.

**Comment by FraMecca** [comment]
Where is test_client_server.py located? I can't find it.

**Comment by aaugustin** [comment]
https://github.com/aaugustin/websockets/blob/master/websockets/test_client_server.py

**Comment by FraMecca** [comment]
I have implemented a test case just by overriding the start_client function in a new test class and repeating all the test for that class using a socket opened using the socket library.

My test class also checks that the socket has effectively been used

**Comment by aaugustin** [comment]
Testing that the socket is actually used is a good idea.

That said I don't think it's a good trade off to duplicate all tests for this because the test suite will take significantly longer. Could you refactor this into a single test?

Then make sure the code matches the coding style (`flake8 websockets`) and I think this will be good to merge.

Thanks!

**Comment by FraMecca** [comment]
The total of the tests takes less than two seconds in my machine. 
Also, I may have explained badly what I did. 

My test class inherits ClientServerTests and replicates all of the class testes except for the one closing the connection before handshake.

There are many that are not needed, for example the ones testing the various headers, but I didn't bother because on my machine my test class has a overhead of 0.2 seconds, bringing the test time from an average of 1.7 seconds to 1.9 seconds.

If you prefer, I may go and examine each test of the ClientServerTest class and remove the ones that are not needed.

**Comment by FraMecca** [comment]
Also, I corrected the code style

**Comment by FraMecca** [comment]
Ok, sounds reasonable.
I'll leave for some days, I'll get to it as soon as I am back home

**Comment by aaugustin** [comment]
Thanks and no hurry!

**Comment by FraMecca** [comment]
Ok, I have reduced the test size using only the test I consider useful for my case.

You should consider using custom rules for flake8 linting because they are too strict (see line 501, client has to be renamed to clnt to avoid >80 chars lines).

**Comment by aaugustin** [comment]
I tried to clean this up in #242 but didn't get to something fully functional.

* I squashed the commits
* I improved the implementation a bit: I kept it functional if the function is called with an explicit `sock=None` parameter)
* I simplified the tests: I believe this needs exactly one test
* I made the test run with and without SSL, which is the interesting variant, as discussed earlier, and which shows a problem with the current implementation:

`ValueError: You must set server_hostname when using ssl without a host`

Since I don't know the use case for a custom `sock` parameter, I'm not sure if we should require users to provide `server_hostname` — and modify the test accordingly — or determine `server_hostname` automatically from the websocket URI.

**Comment by aaugustin** [comment]
Perhaps we should use `server_hostname` if it is provided and fall back to `wsuri.host` if it isn't?

**Comment by FraMecca** [comment]
I think there is no meaningful default.

For example the facebook onion domain has a valid certificate so wsuri.host would be a good guess,
but I have seen in the past invalid ssl certificates on the .onion network.

I think that it is the developer that should provide server_hostname in the same way the custom socket is passed to the parameter of the client.connect.

For this reason I propose to use:
server_hostname = None if not secure else 'localhost' 
on the tests.

**Comment by aaugustin** [comment]
Superseded by #242.

**Pull request closed without merging**
