### PR TITLE
add project_urls metadata

### PR DESCRIPTION
**Pull request by graingert**
specifically I was looking for the Changelog      Changelog=https://websockets.readthedocs.io/en/stable/changelog.html

### CODE REVIEW

**Comment by aaugustin** [comment]
Spec here - https://packaging.python.org/guides/distributing-packages-using-setuptools/#project-urls

**Comment by aaugustin** [comment]
Where does this metadata surface?

I'm a minimalist when it comes to overhead because it requires maintenance and metadata files like `setup.cfg` are overhead.

Searching for "python websockets changelog" in the almighty Google gives the result immediately, which seems a good way find it?

**Comment by graingert** [comment]
It shows up in the sidebar eg https://pypi.org/project/pytest/

**Comment by aaugustin** [comment]
Ah this is nice. Thanks for bringing it up. I'll make the change!

**Comment by aaugustin** [comment]
For the record "standard" names/icons are here:
https://github.com/pypa/warehouse/blob/main/warehouse/templates/packaging/detail.html

**Pull request merged**
