### PR TITLE
Fix issue #309: server.wait_closed()

### PR DESCRIPTION
**Pull request by cjerdonek**
Fixes issue #309.

### CODE REVIEW

**Comment by aaugustin** [comment]
Still working on #309...

Apart from that, the decorator that allows writing async tests is a great idea! Two suggestions to make it even better:

- It could apply `@asyncio.coroutine` automatically to remove the need to stack two decorators on async tests.
- I'm not completely sold on the `@make_sync` name. `@async_test` could work — decorator names usually describe a feature of the object being decorated. Or perhaps `@run_in_event_loop`.

**Comment by aaugustin** [comment]
Currently each test already run it its own event loop:

```
    def setUp(self):
        self.loop = asyncio.new_event_loop()
        asyncio.set_event_loop(self.loop)

    def tearDown(self):
        self.loop.close()
```

**Comment by cjerdonek** [comment]
Oh, right. It's been several months since I looked. What I may have been thinking of then is that there can be different decorators that each do varying levels of setup (e.g. (1) doing nothing other than running the loop, (2) also starting and stopping the server, (3) also starting and stopping the client _and_ server, etc). And depending on things, perhaps it could also make sense to put starting and stopping the loop in the decorators instead of splitting things by putting some logic in the setUp and tearDown and some in the decorators.

**Comment by aaugustin** [comment]
Yes, that makes sense. Good ideas.

**Comment by aaugustin** [comment]
and I neglected websockets for several months as well, nothing wrong with that ;-)

**Comment by aaugustin** [comment]
I filed #403 to follow up on the async test refactor.

**Pull request closed without merging**
