### PR TITLE
Simplify combined consumer-producer example.

### PR DESCRIPTION
**Pull request by cjerdonek**
In the docs [here](https://websockets.readthedocs.io/en/stable/intro.html#both), where you provide an example combining the consumer and producer examples, you say:

> This code looks convoluted. If you know a more straightforward solution, please let me know about it!

This patch provides what seems like the more natural approach. The idea is to use  [`asyncio.gather()`](https://docs.python.org/3/library/asyncio-task.html#asyncio.gather) instead of [`asyncio.wait()`](https://docs.python.org/3/library/asyncio-task.html#asyncio.wait).

I confirmed that this approach works locally.

### CODE REVIEW

**Comment by aaugustin** [comment]
Essentially you're running the producer and consumer coroutines. Indeed, this looks easier than forcing them in the same `while` loop.

```python
        while True:
            await gathered
```

isn't needed as the coroutines don't return.

Actually, with this approach, all you need is:

```python
    async def handler(websocket, path):
        # This call prevents the handler from exiting, which would
        # terminate the websocket connection.
        await asyncio.wait([
            receiver_handler(websocket, path),
            producer_handler(websocket, path),
        ])
```

**Comment by aaugustin** [comment]
I'd like to keep both the "two parallel loops" and "one complicated loop" approaches in the docs, in this order, because this is the sort of thing that needs to click when learning asyncio.

**Comment by cjerdonek** [comment]
> Actually, with this approach, all you need is:

Great!

Should I modify my PR as you described or let you take care of it?

**Comment by cjerdonek** [comment]
I've updated the PR per your suggestions.

**Comment by aaugustin** [comment]
Chris, I'm sorry, but I lost track of this PR and a similar change got committed independently :-(

I preferred a sentence from your version and committed it in 4a57039.

**Comment by cjerdonek** [comment]
@aaugustin No problem, thanks!

**Pull request closed without merging**
