### PR TITLE
fix logging error when send a memoryview

### PR DESCRIPTION
**Pull request by wwqgtxx**
ref https://bugs.python.org/issue15945

### CODE REVIEW

**Comment by aaugustin** [comment]
Thanks for the pull request.

 I would like to add a test for this (because it would be too easy to create a regression otherwise).

**Comment by wwqgtxx** [comment]
Maybe we can simply copy and modify this test code
https://github.com/aaugustin/websockets/blob/498cc8c061e53f0001cb2e3ade22ee8ce5ff11a1/tests/test_frames.py#L273-L278
to add a new test function like this
```python
 def test_binary_memoryview_truncated(self): 
     self.assertEqual( 
         str(Frame(OP_BINARY, memoryview(bytes(range(256))))), 
         "BINARY 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f ..." 
         " f8 f9 fa fb fc fd fe ff [256 bytes]", 
     ) 
```
But maybe we need more test code to cover other places in the code where `memoryview` or even `bytearray` might be passed.

**Comment by aaugustin** [comment]
Yes it's easy :-) I'll take care of it.

**Comment by aaugustin** [comment]
I rebased, added tests in 778879e, and merged. Thank you for your contribution!

**Pull request closed without merging**
