### PR TITLE
TypeError on forced exit

### PR DESCRIPTION
**Pull request by earonesty**
Fixes https://github.com/aaugustin/websockets/issues/317

### CODE REVIEW

**Comment by Gorialis** [comment]
CI fails on this due to the assertion (unreachable within the test suite) - given that the assert is ignored when Python is run in optimization mode (making it not a very good way to raise a backup exception here anyway), I think it can be safely removed.

**Comment by aaugustin** [comment]
I'd rather put an assertion on the connection state than an assert False, as shown in #378.

**Comment by Gorialis** [comment]
Yeah, looks good to me.

**Comment by aaugustin** [comment]
Fixed in 402059e4a46a764632eba8a669f5b012f173ee7b. Thanks for suggesting this approach.

**Pull request closed without merging**
