### PR TITLE
Make select_subprotocol a static method

### PR DESCRIPTION
**Pull request by lgrahl**
As I need to use this function from the outside (feel free to ask why if you want to) and the method can be static, I've made it static. Nothing special. :)

### CODE REVIEW

**Comment by aaugustin** [comment]
Wouldn't this prevent users from subclassing the protocol and implementing a select_protocol that depends on instance variables? I don't know if you can replace a static method by a regular method in a subclass.

**Comment by lgrahl** [comment]
Good question! That shouldn't be a problem, it's even possible to call the inherited method via super:

```python
class A:
    @staticmethod
    def a(arg):
        print(A, arg)

class B(A):
    def a(self, arg):
        super().a(arg)
        print(self, arg)

a = A()
a.a('hello')
b = B()
b.a('hello')
```

**Comment by lgrahl** [comment]
We could also use `@classmethod` instead of `@staticmethod`.

**Comment by aaugustin** [comment]
FTR this change broke the tests on some Python versions because of https://bugs.python.org/issue23078.

**Pull request merged**
