### PR TITLE
Fix exception causes in handshake.py

### PR DESCRIPTION
**Pull request by cool-RR**
That should be the rest of them :)

### CODE REVIEW

**Comment by cool-RR** [comment]
I prefer to have this PR merged first, and then later I'll rebase the other
PR and fix the issues with it. What do you think?

**Comment by aaugustin** [comment]
Yes. This one also conflict with the gigantic refactor in #676. Can we wait a few days to see if the dust settles over there? If I get stuck again, I'll merge this one in a week. I'm sorry for the inconvenience, but every hour wasted rebasing #676 on top of conflicting changes in master is an hour not spent completing it :-/

**Comment by cool-RR** [comment]
Yup, that makes sense. I might push another commit on my other PR, but feel free to ignore it until #676 is finished.

**Comment by aaugustin** [comment]
Now we can move forwards with this :-)

`handshake.py` was renamed to `handshake_legacy.py` since we last talked.

I made a reasonable effort not to introduce new instances of this problem, but that may be worth checking (especially if you found a way to automate this check!)

**Comment by cool-RR** [comment]
LOL, as if my change wasn't esoteric enough, now the entire module. "Anyone who has traveled this far on a fool's errand has no choice but to uphold the honor of fools by completing the errand."

**Comment by cool-RR** [comment]
@aaugustin Want to review this?

**Comment by cool-RR** [comment]
@aaugustin Nudge

**Comment by aaugustin** [comment]
Thanks and sorry for the delay! (on holidays)

**Pull request merged**
