### PR TITLE
Abort pending pings with ConnectionClosed.

### LINKED ISSUE #464: Pong's CancelledError races with ConnectionClosed error
I upgraded to the current version of this library and I find it difficult to handle `asyncio.CancelledError` in case the pong is being cancelled due to a disconnect.

What happens in my server is that I'm waiting for pongs in one task while sending and receiving in another task. Both tasks are being waited for. The result is that in some occasions, `asyncio.CancelledError` is raised before `websockets.ConnectionClosed` and vice versa. When the `asyncio.CancelledError` is raised first, there is no context on why it has been raised.

Another problem with `asyncio.CancelledError` is that there's no way (IIRC) of finding out whether the current task has been cancelled or the task I'm waiting for has been cancelled. But this mainly is an awkward concept of asyncio and not this libraries fault. It seems one has to be extremely careful on when to cancel a task and when not to cancel a task and instead use other ways to signal cancellation (which highly depends on the task). This may clash with the design choice of this library.

TL;DR: I would prefer it if this library would raise `websockets.ConnectionClosed` in the pong's future instead of cancelling the pong.

### PR DESCRIPTION
**Pull request by aaugustin**
Fix #464.

### CODE REVIEW

**Comment by lgrahl** [comment]
I can confirm that this works and fixes my issue. :tada: 

#### Previously

<details><pre><code>[2018-09-04 08:48:07.975708] INFO: saltyrtc.path.1.client.7f6763573128.0x01: Handshake completed
[2018-09-04 08:48:07.975743] DEBUG: saltyrtc.path.1.client.7f6763573128.0x01: Starting to poll for enqueued tasks
[2018-09-04 08:48:07.975775] DEBUG: saltyrtc.path.1.client.7f6763573128.0x01: Starting runner for initiator
[2018-09-04 08:48:07.975812] DEBUG: saltyrtc.path.1.client.7f6763573128.0x01: Starting keep-alive task
[2018-09-04 08:48:08.076217] DEBUG: saltyrtc.path.1.client.7f6763573128.0x01: Ping
[2018-09-04 08:48:08.076298] DEBUG: saltyrtc.path.1.client.7f6763573128.0x01: Sending ping
[2018-09-04 08:48:08.227791] DEBUG: saltyrtc.path.1.client.7f6763573128.0x01: Task done &lt;Task cancelled coro=&lt;ServerProtocol.keep_alive_loop() done, defined at /saltyrtc-server-python/saltyrtc/server/server.py:666>>
[2018-09-04 08:48:08.227901] ERROR: saltyrtc.path.1.client.7f6763573128.0x01: Task &lt;Task cancelled coro=&lt;ServerProtocol.keep_alive_loop() done, defined at /saltyrtc-server-python/saltyrtc/server/server.py:666>> has been cancelled
[2018-09-04 08:48:08.227983] DEBUG: saltyrtc.path.1.client.7f6763573128.0x01: Cancelling task &lt;Task pending coro=&lt;ServerProtocol.task_loop() running at /saltyrtc-server-python/saltyrtc/server/server.py:547> wait_for=&lt;Future pending cb=[&lt;TaskWakeupMethWrapper object at 0x7f676023d1f8>()]>>
[2018-09-04 08:48:08.228106] DEBUG: saltyrtc.path.1.client.7f6763573128.0x01: Cancelling task &lt;Task pending coro=&lt;TestServer.test_disconnect_keep_alive_pong.&lt;locals>._MockProtocol.initiator_receive_loop() running at /saltyrtc-server-python/tests/test_server.py:206> wait_for=&lt;Future finished result=1000>>
[2018-09-04 08:48:08.228207] DEBUG: saltyrtc.path.1.client.7f6763573128.0x01: Cancelling 0 queued tasks
[2018-09-04 08:48:08.228277] ERROR: saltyrtc.path.1.client.7f6763573128.0x01: Closing due to an internal error: A vital task has been cancelled
</code></pre></details>

#### Now

<details><pre><code>[2018-09-04 08:47:37.831338] INFO: saltyrtc.path.1.client.7f9760172828.0x01: Handshake completed
[2018-09-04 08:47:37.831374] DEBUG: saltyrtc.path.1.client.7f9760172828.0x01: Starting to poll for enqueued tasks
[2018-09-04 08:47:37.831407] DEBUG: saltyrtc.path.1.client.7f9760172828.0x01: Starting runner for initiator
[2018-09-04 08:47:37.831448] DEBUG: saltyrtc.path.1.client.7f9760172828.0x01: Starting keep-alive task
[2018-09-04 08:47:37.931866] DEBUG: saltyrtc.path.1.client.7f9760172828.0x01: Ping
[2018-09-04 08:47:37.931951] DEBUG: saltyrtc.path.1.client.7f9760172828.0x01: Sending ping
[2018-09-04 08:47:38.083536] DEBUG: saltyrtc.path.1.client.7f9760172828.0x01: Connection closed while waiting for pong
[2018-09-04 08:47:38.083738] DEBUG: saltyrtc.path.1.client.7f9760172828.0x01: Task done &lt;Task finished coro=&lt;ServerProtocol.keep_alive_loop() done, defined at /saltyrtc-server-python/saltyrtc/server/server.py:666> exception=Disconnected(1000)>
[2018-09-04 08:47:38.083840] DEBUG: saltyrtc.path.1.client.7f9760172828.0x01: Task done &lt;Task finished coro=&lt;TestServer.test_disconnect_keep_alive_pong.&lt;locals>._MockProtocol.initiator_receive_loop() done, defined at /saltyrtc-server-python/tests/test_server.py:203> result=None>
[2018-09-04 08:47:38.083939] DEBUG: saltyrtc.path.1.client.7f9760172828.0x01: Cancelling task &lt;Task pending coro=&lt;ServerProtocol.task_loop() running at /saltyrtc-server-python/saltyrtc/server/server.py:547> wait_for=&lt;Future pending cb=[&lt;TaskWakeupMethWrapper object at 0x7f975ee3b288>()]>>
[2018-09-04 08:47:38.084060] DEBUG: saltyrtc.path.1.client.7f9760172828.0x01: Cancelling 0 queued tasks
[2018-09-04 08:47:38.084131] INFO: saltyrtc.path.1.client.7f9760172828.0x01: Connection closed (code: 1000)
</code></pre></details>

**Comment by aaugustin** [comment]
Great, thanks for testing so quickly!

**Comment by lgrahl** [comment]
@aaugustin Any plans on when this will end up being released?

**Comment by aaugustin** [comment]
I'm going to take a look at open issues over the weekend and tell you.

**Comment by aaugustin** [comment]
I went through the list of open issues this week-end.

I'll make a quick effort to complete #468 (I'm baffled by the failure on CircleCI) and then make a release.

**Comment by aaugustin** [comment]
I'm still hoping to resolve #383 first to avoid making further backwards-incompatible changes in the future.

I had no time for websockets since september; I'm on holidays this week and I hope I can find time to tackle it!

**Pull request merged**
